print (" ------------------------------------- ")
print ("|       Movie Collection Manager      |")
print (" ------------------------------------- ")
print ("|  1. Add a movie                     |")
print ("|  2. View all movie                  |")
print ("|  3. Count watched vs unwatched      |")
print ("|  4. Find a movie                    |")
print ("|  5. Exit                            |")
print (" ------------------------------------- ")

print ()
option = input ("Choose an option: ")